# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=255, unique=True, verbose_name='ISBN Number')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published', models.IntegerField(verbose_name='Year Published')),
                ('genre', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField()),
                ('issued', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.BooleanField()),
                ('transaction_date', models.DateField()),
                ('date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='libraryapp.Book')),
            ],
        ),
    ]
